### ISSUE TITLE
referenced PEOPLE-FixedLength.pzmap.xml not in repo

### ISSUE THREAD

**Issue by criffle** [Appendium/flatpack#12]
I think, at least one of the referenced files from the examples:  PEOPLE-FixedLength.pzmap.xml  - is not in the repository.  Where is this file?

Thanks!

**Comment by criffle** [comment]
Sorry I just saw it: flatpack/flatpack-samples/src/main/script/PEOPLE-FixedLength.pzmap.xml

**Comment by benoitx** [comment]
No prob. Thanks for updating the issue.
