### ISSUE TITLE
DelimiterWriter not consistent with ParserUtils

### ISSUE THREAD

**Issue by antubis23** [Appendium/flatpack#13]
(Tested with 3.4.2)

DelimiterWriter doesn't double qualify text qualifier in string value. 
But ParserUtils assumes excel like format for text qualifier in quoted string (qualifiers doubled).
Simple test for consuming self written content:
	@Test
	public void testWriteRead() throws IOException {

		final java.io.Writer writer = new StringWriter();

		final Set<String> header = new LinkedHashSet<String>();
		header.add("Header1");
		header.add("Header2");
		header.add("Header3");

		final List<Map<String, String>> dataList = new ArrayList<Map<String, String>>();
		for (int i = 0; i < 2; i++) {
			final Map<String, String> tempMap = new HashMap<String, String>(header.size());
			for (final String it : header) {
				tempMap.put(it, it + "_" + "Data \"\" " + i + " \"");
			}
			dataList.add(tempMap);
		}
		final DelimiterWriterFactory delimiterWriterFactory = new DelimiterWriterFactory(';', '"');
		for (final String it : header) {
			delimiterWriterFactory.addColumnTitle(it);
		}
		final Writer createWriter = delimiterWriterFactory.createWriter(writer, WriterOptions.getInstance().autoPrintHeader(true));

		for (final Map<String, String> data : dataList) {
			for (final Map.Entry<String, String> entry : data.entrySet() ) {
				createWriter.addRecordEntry(entry.getKey(), entry.getValue());
			}
			createWriter.nextRecord();
		}
		createWriter.flush();
		final ByteArrayInputStream file = new ByteArrayInputStream(writer.toString().getBytes());
		final DelimiterParser parser = new DelimiterParser(file, ';', '"', false);
		final DataSet parse = parser.parse();
		parse.next();
		final Record record = parse.getRecord();
		assertEquals("Header2_Data \"\" 0 \"", record.getString("Header2"));
	}

It should at least be able to parse it own created content.

**Comment by benoitx** [comment]
Hi

Thanks for raising this and providing a test.

 I will try to have a look "soon"..
regards

Benoit

**Comment by ks-appendium** [comment]
@benoitx Fixed on master. Are we back-porting to 3.4.x branch as well?

**Comment by benoitx** [comment]
@ks-appendium yes please, is it backported to 3.4 ?
