### ISSUE TITLE
Error executing LargeDelimitedWithPZMap in package package net.sf.flatpack.examples.largedataset.delimiteddynamiccolumns

### ISSUE THREAD

**Issue by rahulsbz** [Appendium/flatpack#14]
Hello Team,

While executing the LargeDelimitedWithPZMap I get the following Error "java.lang.NullPointerException
	at net.sf.flatpack.DefaultDataSet.getString"

It appears that the DefaultDataSet" currentRecord is not set on DefaultDataSet object when ds.next() is called on BuffReaderDataSet

Thanks, Rahul

**Comment by benoitx** [comment]
Hi

Could you provide a test case please?
Many thanks 
B

-----
Important Notice
This communication contains information that is considered
confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any form of distribution, copying or use of this communication or the
information in it is strictly prohibited and may be unlawful. If you have received this communication in error please return it to the sender and
delete the original

**Comment by moffatn** [comment]
Hi,

I'm seeing this as well.  I had to amend the BuffReaderDataSet.next() method to call super.next() to set the currentRecord, see:

https://gist.github.com/moffatn/4fa5be4e5bb3b81133ae

**Comment by ks-appendium** [comment]
Can you please post the stack trace and sample invoking client code and we will take a look

**Comment by benoitx** [comment]
Please try release 3.4.3 or 4.0.1 (java 8).
Kindly let us know if this fixes the issue.
Thanks for your help

**Comment by moffatn** [comment]
Thanks, 4.0.1 is working for me.
