### ISSUE TITLE
Mark jxl imports optional in OSGi

### ISSUE THREAD

**Issue by dkulp** [Appendium/flatpack#16]
Currently, the jxl imports are not marked as optional in the MANIFEST for the OSGi metadata.   This causes a problem for projects wishing to use flatpack for non-Excel use cases as that requires jexcelapi to be installed which is licensed LGPL.   For example, Apache projects cannot pull that in.   It would be great if those imports can be marked optional.

This would be needed for 3.4.x.

**Comment by benoitx** [comment]
Hi 
Could you try the latest 3.4.3-SNAPSHOT in the Snapshot repo?
https://oss.sonatype.org/content/repositories/snapshots/net/sf/flatpack/flatpack/3.4.3-SNAPSHOT/

Let us know if it fixes your issue

Thanks

**Comment by dkulp** [comment]
Seems to work perfectly.   Thanks!   (any idea when a release may occur?)

**Comment by benoitx** [comment]
I'll check with my colleague.
Soon hopefully we have fixed a couple of items recently.

**Comment by benoitx** [comment]
I'll try to push a release this weekend.

**Comment by benoitx** [comment]
Please try release 3.4.3 or 4.0.1 (java 8).
Let us know. Thanks
