### ISSUE TITLE
Support for COBOL packed decimal data format and EBCDIC support

### ISSUE THREAD

**Issue by srbala** [Appendium/flatpack#21]
I am new to flatpack library.Support for COBOL packed decimal data format and EBCDIC support, not sure flatpack supports it.

Scanned through documentation and samples, I am not able to locate how to read/write COBOL packed decimal data COMP, COMP-3 etc.

Is flatpack support these? if not, any plan to support in future?

**Comment by benoitx** [comment]
Hi

Could you provide an example how this big decimal is represented in text?

You can use FlatPack to get strings out of the file, you would then simply need to parse the string.

HTH

Benoit

-----
Important Notice
This communication contains information that is considered
confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any form of distribution, copying or use of this communication or the
information in it is strictly prohibited and may be unlawful. If you have received this communication in error please return it to the sender and
delete the original

**Comment by srbala** [comment]
Packed data is applicable only for binary data format. I will find for some spec and post it here.

**Comment by benoitx** [comment]
So your question would be...does FlatPack handle binary files with a definition for fixed width?

Good question...I have never tried...I doubt there won't be any glitches... Would love if you could try it and let us know.

Thanks 

-----
Important Notice
This communication contains information that is considered
confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any form of distribution, copying or use of this communication or the
information in it is strictly prohibited and may be unlawful. If you have received this communication in error please return it to the sender and
delete the original

**Comment by srbala** [comment]
No longer required tihs feature, closing issue.
