### ISSUE TITLE
add key / indicator to record interface

### ISSUE THREAD

**Issue by ronnyaerts** [Appendium/flatpack#23]
I have to do several fixed-length conversions where I have a lot of differences per line in the file. Each line contains some kind of record type field the beginning of the line. The pzmap/record definitions are perfect to satisfy my requests so the conversion itself is ok for me. 
I do however have some issues converting the result DefaultDataSet to xml. It would be very good for me that the record interface publishes the "row" or at least the mdkey of the row/record. Now when I loop thru the dataset, I have to go thru the metadata and getting all keys to see if it matches using the isRecordID method. 
The attachment shows how I retrieve the record key using the getRecordKey methode.

I use flatpack in combination with apache camel. 

[show-dataset.js.txt](https://github.com/Appendium/flatpack/files/120306/show-dataset.js.txt)

**Comment by benoitx** [comment]
Hi

Thanks for contacting us. This is quite a coincidence as I'm currently on a project that deal with a lot of fixed width records as well.

As a matter of fact I have added a getRecordID method on the DataSet and Record interfaces.

A snapshot 4.0.2 is available on the snapshot repository.  Could you have a go with it and let me know if that is working for you?

Best regards

Benoit

-----
Important Notice
This communication contains information that is considered
confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any form of distribution, copying or use of this communication or the
information in it is strictly prohibited and may be unlawful. If you have received this communication in error please return it to the sender and
delete the original

**Comment by ronnyaerts** [comment]
Where do I find the git link to the 4.0.2 snapshot.

**Comment by benoitx** [comment]
It is the official repository 
4.0.2 is not released yet but if you clone master you will have it

A jar file is available on the Sonatype snapshot maven repo. I'll send you the link later on as I'm out right now.

Benoit

-----
Important Notice
This communication contains information that is considered
confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any form of distribution, copying or use of this communication or the
information in it is strictly prohibited and may be unlawful. If you have received this communication in error please return it to the sender and
delete the original

**Comment by ronnyaerts** [comment]
I just did I clone and pull on https://github.com/Appendium/flatpack.git. The last comment on the master branch is "describe changes" on 29-jan-2016. None of the files contain a getRecordID.

**Comment by benoitx** [comment]
Sorry about that it might still be internal.

I'll ensure that it is pushed tonight and drop you a note.

Benoit

-----
Important Notice
This communication contains information that is considered
confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any form of distribution, copying or use of this communication or the
information in it is strictly prohibited and may be unlawful. If you have received this communication in error please return it to the sender and
delete the original

**Comment by benoitx** [comment]
A snapshot is available at:

https://oss.sonatype.org/content/repositories/snapshots/net/sf/flatpack/flatpack-examples/4.0.2-SNAPSHOT/

Let me know

Thanks

Benoit

On 6 February 2016 at 17:10, <bx@appendium.com> wrote:

> Sorry about that it might still be internal.
>
> I'll ensure that it is pushed tonight and drop you a note.
>
> Benoit
>
> -----
> Important Notice
> This communication contains information that is considered
> confidential and may also be privileged. It is for the exclusive use of
> the intended recipient(s). If you are not the intended recipient(s)
> please note that any form of distribution, copying or use of this
> communication or the
> information in it is strictly prohibited and may be unlawful. If you have received
> this communication in error please return it to the sender and
> delete the original
>
> On 6 Feb 2016, at 16:52, ronnyaerts <notifications@github.com> wrote:
>
> I just did I clone and pull on https://github.com/Appendium/flatpack.git.
> The last comment on the master branch is "describe changes" on 29-jan-2016.
> None of the files contain a getRecordID.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Appendium/flatpack/issues/23#issuecomment-180809122>.
>
>


-- 
Follow us on Twitter @appendium <http://twitter.com/appendium> and
http://www.appendium.com
----

IMPORTANT NOTICE This communication contains information that is considered
confidential and may also be privileged . It is for the exclusive use of
the intended recipient(s). If you are not the intended recipient(s) please
note that any form of distribution, copying or use of this communication or
the information in it is strictly prohibited and may be unlawful. If you
have received this communication in error please return it to the sender
and delete the original.

**Comment by ronnyaerts** [comment]
I did a pull and the modifications look promising. I'll try to build it into apache camel on monday.

**Comment by ronnyaerts** [comment]
The changes work as expected.

Thank you for the change.

**Comment by benoitx** [comment]
Excellent. Thanks for the feedback.

**Comment by ronnyaerts** [comment]
Hello Benoit,

Is it possible that the flatpack 4.0.2-SNAPSHOT is not available anymore in maven central<http://mvnrepository.com/artifact/net.sf.flatpack/flatpack>?

--
Kind regards,
Ronny Aerts<mailto:ronny.aerts@intris.be> – Intris nv – Wapenstilstandlaan 47, 2600 Berchem, Belgium
R&D Integration Architect
Prince II<http://en.wikipedia.org/wiki/PRINCE2> certified – ITIL<http://en.wikipedia.org/wiki/Information_Technology_Infrastructure_Library> certified
Tel: +32-3-326.50.75

**Comment by benoitx** [comment]
Hi

It should be available on the snapshot repo from sonatype

Https://oss.sonatype.org/content/repositories/snapshots/net/sf/flatpack/

Let me know if it is ok

I'll probably do a release this month

Regards

Benoit

-----
Important Notice
This communication contains information that is considered
confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any form of distribution, copying or use of this communication or the
information in it is strictly prohibited and may be unlawful. If you have received this communication in error please return it to the sender and
delete the original

**Comment by ronnyaerts** [comment]
Hello Benoit,

I added the sonatype repository to my maven settings and now I can retrieve the version.

--
Kind regards,
Ronny Aerts<mailto:ronny.aerts@intris.be> – Intris nv – Wapenstilstandlaan 47, 2600 Berchem, Belgium
R&D Integration Architect
Prince II<http://en.wikipedia.org/wiki/PRINCE2> certified – ITIL<http://en.wikipedia.org/wiki/Information_Technology_Infrastructure_Library> certified
Tel: +32-3-326.50.75
