### ISSUE TITLE
Metadata not set when using BuffReader delimited parser with column names in file

### ISSUE THREAD

**Issue by gorankl** [Appendium/flatpack#24]
When using:

`BuffReaderParseFactory.getInstance().newDelimitedParser(reader, ',', '"')`

where reader reads from csv file with column names,
metadata of DataSet is not set, causing NPE when reading from dataset.

**Comment by gorankl** [comment]
Created pull request: #25

**Comment by r3t0x** [comment]
Is there an ETA for when this will be merged?

**Comment by benoitx** [comment]
Merged, many thanks for the contribution.
